server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  # /etc/hosts
  client:
    #false表明不用向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/   # 相互注册 相互守望 集群需要能够找到7002的机子  单机就是自己 集群就要写其他人