server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  # /etc/hosts
  client:
    #false表明不用向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      # 单机版本
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/   # 相互注册 相互守望 集群需要能够找到7002的机子
  server:
    # 关闭自我保护机制 保证不可用服务及时被剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000